Importing the libraries

In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
dataset = pd.read_csv("train.csv")
X = dataset.iloc[:, 1:].values # [all rows, everything after 1st column]
y = dataset.iloc[:, 0].values # [all rows, only 1st column]

In [ ]:
dataset.head()

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [ ]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(y)

[1 0 1 ... 7 6 9]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y_train

array([5, 1, 0, ..., 0, 0, 6])

In [ ]:
y_test

array([6, 5, 9, ..., 3, 5, 2])

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from sklearn.svm import SVC #SVM

classifier = SVC(kernel = 'rbf')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[6 6]
 [5 5]
 [9 9]
 ...
 [3 3]
 [5 5]
 [2 2]]


In [ ]:
y_pred

array([6, 5, 9, ..., 3, 5, 2])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[836   0   2   0   0   3   5   0   2   0]
 [  0 961   9   4   2   0   0   2   3   1]
 [  2   3 814   4   3   0   1   8   7   0]
 [  1   3  14 854   1  10   1   6   5   2]
 [  1   0  12   0 766   2   2   3   2  15]
 [  2   0   5   6   3 693   9   2   7   0]
 [  2   1  16   0   2   5 812   0   1   0]
 [  1   2  17   0   9   0   0 829   1  15]
 [  2   3   6   3   2   6   4   1 731   1]
 [  2   2  11   5  12   5   0  12   5 775]]


0.9608333333333333

In [ ]:
test_dataset = pd.read_csv("test.csv")
test_X = test_dataset.iloc[:, :].values

In [ ]:
y_results = sc.fit_transform(test_X)

In [ ]:
y_results = classifier.predict(y_results)

In [ ]:
y_results

array([2, 0, 9, ..., 3, 9, 2])

In [ ]:
y_results.reshape(len(y_results), 1)


array([[2],
       [0],
       [9],
       ...,
       [3],
       [9],
       [2]])

In [ ]:
import csv 
header = ["ImageId", "Label"]

def create_csv(results):
 with open('submission.csv', 'w', newline= '') as file:
  id = 1
  index = 0
  
  writer = csv.DictWriter(file, fieldnames = header) 
  writer.writeheader()
  for i in range(0, len(results)):
    writer.writerow({
        header[0]: id,
        header[1]: results[index]
    })
    id += 1
    index += 1

In [ ]:
create_csv(y_results)